### Get all students - OK
GET http://localhost:3000/api/students

### Create Student - OK
POST http://localhost:3000/api/students
Content-Type: application/json

{
    "firstName": "Juan Jose",
    "lastName": "Puente Scapolatempo"
}