### Create authors - POST
POST http://localhost:8080/api/situations/populate/create-author
Content-Type: application/json

{
    "firstName": "Juan Jose",
    "lastName": "Puente"
}

### Create Books - POST
POST http://localhost:8080/api/situations/populate/create-book
Content-Type: application/json

{
    "name": "Docker - Contenedores e instancias",
    "description": "Libro sobre contenedores de docker",
    "authorId": "658ca210820239cdd712cc9f"
}

### Find books - All - GET
GET http://localhost:8080/api/situations/populate/find-books

### Find books - All - AuthorData - GET
GET http://localhost:8080/api/situations/populate/find-books?withAuthorData=YES

### Find books - By Book Id - GET
GET http://localhost:8080/api/situations/populate/find-books?bookId=658ca294820239cdd712cca1

### Find books - By Book Id - AuthorData - GET
GET http://localhost:8080/api/situations/populate/find-books?bookId=65836a01e1c3be79ee0a4473&withAuthorData=YES